### ISSUE TITLE
Factories without correct blocks are not loaded

### ISSUE THREAD

**Issue by gmlaxfanatic** [gmlaxfanatic/FactoryMod#42]

**Comment by UselessFodder** [comment]
Can we clean up the various extra issues that have been resolved? I'm trying to see what still needs working on.

**Comment by gmlaxfanatic** [comment]
I think this is still present. I haven't gotten to it since the rewrite I'm doing fixes it, Its just a pretty massive rewrite so its taking a while :(. Looking at the list #42, #38, #30, #21 should all be fixed with the rewrite, #20 will not be fixed in the rewrite.
